-- plugins/which-key.lua
-- Keymap discovery and documentation

return {
	"folke/which-key.nvim",
	event = "VeryLazy",
	opts = {
		plugins = {
			marks = true,
			registers = true,
			spelling = {
				enabled = true,
				suggestions = 20,
			},
			presets = {
				operators = true,
				motions = true,
				text_objects = true,
				windows = true,
				nav = true,
				z = true,
				g = true,
			},
		},
		win = {
			border = "rounded",
			padding = { 2, 2, 2, 2 },
		},
	},
	config = function(_, opts)
		local wk = require("which-key")
		wk.setup(opts)
		wk.add({
			{ "<leader>b", desc = "Find buffers" },
			{ "<leader>a", group = "Code Action" },
			{ "<leader>A", group = "Add" },
			{ "<leader>Aw", desc = "Add word to cspell" },
			{ "<leader>d", desc = "Show diagnostic" },
			{ "<leader>D", desc = "Diagnostics quickfix" },
			{ "<leader>e", desc = "Toggle Neo-tree" },
			{ "<leader>E", desc = "Reveal file in Neo-tree" },
			{ "<leader>f", desc = "Find files" },
			{ "<leader>g", desc = "Grep search" },
			{ "<leader>G", group = "git" },
			{ "<leader>GB", desc = "Blame line" },
			{ "<leader>Gb", desc = "Toggle line blame" },
			{ "<leader>GD", desc = "Diff this" },
			{ "<leader>Gd", desc = "Toggle deleted" },
			{ "<leader>Gh", group = "git hunks" },
			{ "<leader>Ghs", desc = "Stage hunk" },
			{ "<leader>Ghr", desc = "Reset hunk" },
			{ "<leader>GhS", desc = "Stage buffer" },
			{ "<leader>Ghu", desc = "Undo stage hunk" },
			{ "<leader>GhR", desc = "Reset buffer" },
			{ "<leader>Ghp", desc = "Preview hunk" },
			{ "<leader>Ghd", desc = "Diff this ~" },
			{ "<leader>h", desc = "Recent files" },
			{ "<leader>k", desc = "Show keymaps" },
			{ "<leader>m", group = "Markdown" },
			{ "<leader>mp", desc = "Toggle Markdown Preview" },
			{ "<leader>o", desc = "Toggle Aerial" },
			{ "<leader>p", group = "Packages" },
			{ "<leader>pm", desc = "Mason" },
			{ "<leader>q", group = "Session" },
			{ "<leader>qs", desc = "Restore Session" },
			{ "<leader>ql", desc = "Restore Last Session" },
			{ "<leader>qd", desc = "Don't Save Current Session" },
			{ "<leader>qS", desc = "Select a session to load" },
			{ "<leader>r", desc = "Show registers" },
			{ "<leader>R", desc = "Rename symbol" },
			{ "<leader>s", desc = "Save file" },
			{ "<leader>u", group = "User Interface" },
			{ "<leader>un", desc = "Dismiss all notifications" },
			{ "<leader>w", desc = "Close buffer" },
			{ "<leader>x", group = "Diagnostics" },
			{ "<leader>xL", desc = "Location List (Trouble)" },
			{ "<leader>xl", desc = "LSP Definitions / references / ... (Trouble)" },
			{ "<leader>xQ", desc = "Quickfix List (Trouble)" },
			{ "<leader>xs", desc = "Symbols (Trouble)" },
			{ "<leader>xt", desc = "Todo (Trouble)" },
			{ "<leader>xT", desc = "Todo/Fix/Fixme (Trouble)" },
			{ "<leader>xX", desc = "Buffer Diagnostics (Trouble)" },
			{ "<leader>xx", desc = "Diagnostics (Trouble)" },
		})
	end,
}
